version: '3.13'

networks:
  dev:

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=<YOUR_MINIO_ROOT_USER>
      - MINIO_ROOT_PASSWORD=<YOUR_MINIO_ROOT_PASSWORD>
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - dev

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 <YOUR_MINIO_ROOT_USER> <YOUR_MINIO_ROOT_PASSWORD> && mc mb myminio/wh-support-tmp && mc mb myminio/wh-support && mc admin user add myminio <YOUR_MINIO_USER> <YOUR_MINIO_USER_PASSWORD> && mc admin policy attach myminio readwrite --user <YOUR_MINIO_USER>); do sleep 5; done"
    networks:
      - dev