### Отправка сообщения
POST {{host}}/api/chat/create_post?employee_id={{employee_id}}
Authorization: Basic {{basicAuth}}
Content-Type: application/json

{
  "ticket_id": 125,
  "message": "new message"
}

### 422 Заявка не существует
POST {{host}}/api/chat/create_post?employee_id={{employee_id}}
Authorization: Basic {{basicAuth}}
Content-Type: application/json

{
  "ticket_id": 126,
  "message": "new message"
}

### 403 У пользователя нет прав
POST {{host}}/api/chat/create_post?employee_id={{employee_id}}
Authorization: Basic {{basicAuth}}
Content-Type: application/json

{
  "ticket_id": 127,
  "message": "new message"
}
