// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: support.tickets.category.statuses.proto

package sync_models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryStatuses struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          []*CategoryStatuses_CategoryStatus `protobuf:"bytes,1,rep,name=Data,proto3" json:"data" binding:"required,gt=0,dive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStatuses) Reset() {
	*x = CategoryStatuses{}
	mi := &file_support_tickets_category_statuses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStatuses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStatuses) ProtoMessage() {}

func (x *CategoryStatuses) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_category_statuses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStatuses.ProtoReflect.Descriptor instead.
func (*CategoryStatuses) Descriptor() ([]byte, []int) {
	return file_support_tickets_category_statuses_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryStatuses) GetData() []*CategoryStatuses_CategoryStatus {
	if x != nil {
		return x.Data
	}
	return nil
}

type CategoryStatuses_CategoryStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryID         int64                  `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"category_id" binding:"required"`
	StatusID           string                 `protobuf:"bytes,2,opt,name=StatusID,proto3" json:"status_id" binding:"required,len=3"`
	StatusDescription  string                 `protobuf:"bytes,3,opt,name=StatusDescription,proto3" json:"status_description" binding:"required"`
	GroupID            *int64                 `protobuf:"varint,4,opt,name=GroupID,proto3,oneof" json:"group_id" binding:"omitempty"`
	IsDel              *bool                  `protobuf:"varint,5,opt,name=IsDel,proto3,oneof" json:"is_del" binding:"required"`
	ChEmployeeID       int64                  `protobuf:"varint,6,opt,name=ChEmployeeID,proto3" json:"ch_employee_id" binding:"required"`
	ChDt               string                 `protobuf:"bytes,7,opt,name=ChDt,proto3" json:"ch_dt" binding:"required,IsRFC3339Nano"`
	ConstructorOrderID int64                  `protobuf:"varint,8,opt,name=ConstructorOrderID,proto3" json:"constructor_order_id" binding:"required,gt=0"`
	LogId              int64                  `protobuf:"varint,100,opt,name=LogId,proto3" json:"log_id"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryStatuses_CategoryStatus) Reset() {
	*x = CategoryStatuses_CategoryStatus{}
	mi := &file_support_tickets_category_statuses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStatuses_CategoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStatuses_CategoryStatus) ProtoMessage() {}

func (x *CategoryStatuses_CategoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_category_statuses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStatuses_CategoryStatus.ProtoReflect.Descriptor instead.
func (*CategoryStatuses_CategoryStatus) Descriptor() ([]byte, []int) {
	return file_support_tickets_category_statuses_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CategoryStatuses_CategoryStatus) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *CategoryStatuses_CategoryStatus) GetStatusID() string {
	if x != nil {
		return x.StatusID
	}
	return ""
}

func (x *CategoryStatuses_CategoryStatus) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *CategoryStatuses_CategoryStatus) GetGroupID() int64 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *CategoryStatuses_CategoryStatus) GetIsDel() bool {
	if x != nil && x.IsDel != nil {
		return *x.IsDel
	}
	return false
}

func (x *CategoryStatuses_CategoryStatus) GetChEmployeeID() int64 {
	if x != nil {
		return x.ChEmployeeID
	}
	return 0
}

func (x *CategoryStatuses_CategoryStatus) GetChDt() string {
	if x != nil {
		return x.ChDt
	}
	return ""
}

func (x *CategoryStatuses_CategoryStatus) GetConstructorOrderID() int64 {
	if x != nil {
		return x.ConstructorOrderID
	}
	return 0
}

func (x *CategoryStatuses_CategoryStatus) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

var File_support_tickets_category_statuses_proto protoreflect.FileDescriptor

const file_support_tickets_category_statuses_proto_rawDesc = "" +
	"\n" +
	"'support.tickets.category.statuses.proto\x12\vsync_models\x1a)github.com/alta/protopatch/patch/go.proto\"\xf3\x06\n" +
	"\x10CategoryStatuses\x12q\n" +
	"\x04Data\x18\x01 \x03(\v2,.sync_models.CategoryStatuses.CategoryStatusB/ʵ\x03+\xa2\x01(json:\"data\" binding:\"required,gt=0,dive\"R\x04Data\x1a\xeb\x05\n" +
	"\x0eCategoryStatus\x12L\n" +
	"\n" +
	"CategoryID\x18\x01 \x01(\x03B,ʵ\x03(\xa2\x01%json:\"category_id\" binding:\"required\"R\n" +
	"CategoryID\x12L\n" +
	"\bStatusID\x18\x02 \x01(\tB0ʵ\x03,\xa2\x01)json:\"status_id\" binding:\"required,len=3\"R\bStatusID\x12a\n" +
	"\x11StatusDescription\x18\x03 \x01(\tB3ʵ\x03/\xa2\x01,json:\"status_description\" binding:\"required\"R\x11StatusDescription\x12I\n" +
	"\aGroupID\x18\x04 \x01(\x03B*ʵ\x03&\xa2\x01#json:\"group_id\" binding:\"omitempty\"H\x00R\aGroupID\x88\x01\x01\x12B\n" +
	"\x05IsDel\x18\x05 \x01(\bB'ʵ\x03#\xa2\x01 json:\"is_del\" binding:\"required\"H\x01R\x05IsDel\x88\x01\x01\x12S\n" +
	"\fChEmployeeID\x18\x06 \x01(\x03B/ʵ\x03+\xa2\x01(json:\"ch_employee_id\" binding:\"required\"R\fChEmployeeID\x12H\n" +
	"\x04ChDt\x18\a \x01(\tB4ʵ\x030\xa2\x01-json:\"ch_dt\" binding:\"required,IsRFC3339Nano\"R\x04ChDt\x12j\n" +
	"\x12ConstructorOrderID\x18\b \x01(\x03B:ʵ\x036\xa2\x013json:\"constructor_order_id\" binding:\"required,gt=0\"R\x12ConstructorOrderID\x12*\n" +
	"\x05LogId\x18d \x01(\x03B\x14ʵ\x03\x10\xa2\x01\rjson:\"log_id\"R\x05LogIdB\n" +
	"\n" +
	"\b_GroupIDB\b\n" +
	"\x06_IsDelB\x0fZ\r./sync_modelsb\x06proto3"

var (
	file_support_tickets_category_statuses_proto_rawDescOnce sync.Once
	file_support_tickets_category_statuses_proto_rawDescData []byte
)

func file_support_tickets_category_statuses_proto_rawDescGZIP() []byte {
	file_support_tickets_category_statuses_proto_rawDescOnce.Do(func() {
		file_support_tickets_category_statuses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_tickets_category_statuses_proto_rawDesc), len(file_support_tickets_category_statuses_proto_rawDesc)))
	})
	return file_support_tickets_category_statuses_proto_rawDescData
}

var file_support_tickets_category_statuses_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_support_tickets_category_statuses_proto_goTypes = []any{
	(*CategoryStatuses)(nil),                // 0: sync_models.CategoryStatuses
	(*CategoryStatuses_CategoryStatus)(nil), // 1: sync_models.CategoryStatuses.CategoryStatus
}
var file_support_tickets_category_statuses_proto_depIdxs = []int32{
	1, // 0: sync_models.CategoryStatuses.Data:type_name -> sync_models.CategoryStatuses.CategoryStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_support_tickets_category_statuses_proto_init() }
func file_support_tickets_category_statuses_proto_init() {
	if File_support_tickets_category_statuses_proto != nil {
		return
	}
	file_support_tickets_category_statuses_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_tickets_category_statuses_proto_rawDesc), len(file_support_tickets_category_statuses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_support_tickets_category_statuses_proto_goTypes,
		DependencyIndexes: file_support_tickets_category_statuses_proto_depIdxs,
		MessageInfos:      file_support_tickets_category_statuses_proto_msgTypes,
	}.Build()
	File_support_tickets_category_statuses_proto = out.File
	file_support_tickets_category_statuses_proto_goTypes = nil
	file_support_tickets_category_statuses_proto_depIdxs = nil
}
