// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: support.tickets.changes.proto

package sync_models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tickets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Tickets_Ticket      `protobuf:"bytes,1,rep,name=Data,proto3" json:"data" binding:"required,gt=0,dive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tickets) Reset() {
	*x = Tickets{}
	mi := &file_support_tickets_changes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tickets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tickets) ProtoMessage() {}

func (x *Tickets) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_changes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tickets.ProtoReflect.Descriptor instead.
func (*Tickets) Descriptor() ([]byte, []int) {
	return file_support_tickets_changes_proto_rawDescGZIP(), []int{0}
}

func (x *Tickets) GetData() []*Tickets_Ticket {
	if x != nil {
		return x.Data
	}
	return nil
}

type Tickets_Ticket struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TicketID           int64                  `protobuf:"varint,1,opt,name=TicketID,proto3" json:"ticket_id" binding:"required"`
	CategoryID         int64                  `protobuf:"varint,2,opt,name=CategoryID,proto3" json:"category_id" binding:"required"`
	CategoryName       string                 `protobuf:"bytes,3,opt,name=CategoryName,proto3" json:"category_name" binding:"required"`
	ParentCategoryName string                 `protobuf:"bytes,4,opt,name=ParentCategoryName,proto3" json:"parent_category_name" binding:"required"`
	StatusID           string                 `protobuf:"bytes,5,opt,name=StatusID,proto3" json:"status_id" binding:"required,len=3"`
	StatusDescription  string                 `protobuf:"bytes,6,opt,name=StatusDescription,proto3" json:"status_description" binding:"required"`
	StatusEmployeeID   int64                  `protobuf:"varint,7,opt,name=StatusEmployeeID,proto3" json:"status_employee_id" binding:"required"`
	StatusGroupName    *string                `protobuf:"bytes,8,opt,name=StatusGroupName,proto3,oneof" json:"status_group_name" binding:"omitempty"`
	ScenarioOrderID    *int64                 `protobuf:"varint,9,opt,name=ScenarioOrderID,proto3,oneof" json:"scenario_order_id" binding:"omitempty"`
	ScenarioName       *string                `protobuf:"bytes,10,opt,name=ScenarioName,proto3,oneof" json:"scenario_name" binding:"omitempty"`
	RejectedComment    *string                `protobuf:"bytes,11,opt,name=RejectedComment,proto3,oneof" json:"rejected_comment" binding:"omitempty"`
	Ext                []*Tickets_ExtData     `protobuf:"bytes,12,rep,name=Ext,proto3" json:"ext" binding:"omitempty,dive"`
	ChDt               string                 `protobuf:"bytes,13,opt,name=ChDt,proto3" json:"ch_dt" binding:"required"`
	CreateEmployeeID   int64                  `protobuf:"varint,14,opt,name=CreateEmployeeID,proto3" json:"create_employee_id" binding:"required"`
	CreateDt           string                 `protobuf:"bytes,15,opt,name=CreateDt,proto3" json:"create_dt" binding:"required"`
	LogId              int64                  `protobuf:"varint,100,opt,name=LogId,proto3" json:"log_id"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Tickets_Ticket) Reset() {
	*x = Tickets_Ticket{}
	mi := &file_support_tickets_changes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tickets_Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tickets_Ticket) ProtoMessage() {}

func (x *Tickets_Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_changes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tickets_Ticket.ProtoReflect.Descriptor instead.
func (*Tickets_Ticket) Descriptor() ([]byte, []int) {
	return file_support_tickets_changes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Tickets_Ticket) GetTicketID() int64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

func (x *Tickets_Ticket) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Tickets_Ticket) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Tickets_Ticket) GetParentCategoryName() string {
	if x != nil {
		return x.ParentCategoryName
	}
	return ""
}

func (x *Tickets_Ticket) GetStatusID() string {
	if x != nil {
		return x.StatusID
	}
	return ""
}

func (x *Tickets_Ticket) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *Tickets_Ticket) GetStatusEmployeeID() int64 {
	if x != nil {
		return x.StatusEmployeeID
	}
	return 0
}

func (x *Tickets_Ticket) GetStatusGroupName() string {
	if x != nil && x.StatusGroupName != nil {
		return *x.StatusGroupName
	}
	return ""
}

func (x *Tickets_Ticket) GetScenarioOrderID() int64 {
	if x != nil && x.ScenarioOrderID != nil {
		return *x.ScenarioOrderID
	}
	return 0
}

func (x *Tickets_Ticket) GetScenarioName() string {
	if x != nil && x.ScenarioName != nil {
		return *x.ScenarioName
	}
	return ""
}

func (x *Tickets_Ticket) GetRejectedComment() string {
	if x != nil && x.RejectedComment != nil {
		return *x.RejectedComment
	}
	return ""
}

func (x *Tickets_Ticket) GetExt() []*Tickets_ExtData {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *Tickets_Ticket) GetChDt() string {
	if x != nil {
		return x.ChDt
	}
	return ""
}

func (x *Tickets_Ticket) GetCreateEmployeeID() int64 {
	if x != nil {
		return x.CreateEmployeeID
	}
	return 0
}

func (x *Tickets_Ticket) GetCreateDt() string {
	if x != nil {
		return x.CreateDt
	}
	return ""
}

func (x *Tickets_Ticket) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type Tickets_ExtData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontDataName string                 `protobuf:"bytes,1,opt,name=FrontDataName,proto3" json:"front_data_name" binding:"required"`
	DataName      string                 `protobuf:"bytes,2,opt,name=DataName,proto3" json:"data_name" binding:"required"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=Value,proto3" json:"value" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tickets_ExtData) Reset() {
	*x = Tickets_ExtData{}
	mi := &file_support_tickets_changes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tickets_ExtData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tickets_ExtData) ProtoMessage() {}

func (x *Tickets_ExtData) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_changes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tickets_ExtData.ProtoReflect.Descriptor instead.
func (*Tickets_ExtData) Descriptor() ([]byte, []int) {
	return file_support_tickets_changes_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Tickets_ExtData) GetFrontDataName() string {
	if x != nil {
		return x.FrontDataName
	}
	return ""
}

func (x *Tickets_ExtData) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

func (x *Tickets_ExtData) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_support_tickets_changes_proto protoreflect.FileDescriptor

const file_support_tickets_changes_proto_rawDesc = "" +
	"\n" +
	"\x1dsupport.tickets.changes.proto\x12\vsync_models\x1a\x1cgoogle/protobuf/struct.proto\x1a)github.com/alta/protopatch/patch/go.proto\"\x9a\x0e\n" +
	"\aTickets\x12`\n" +
	"\x04Data\x18\x01 \x03(\v2\x1b.sync_models.Tickets.TicketB/ʵ\x03+\xa2\x01(json:\"data\" binding:\"required,gt=0,dive\"R\x04Data\x1a\xaa\v\n" +
	"\x06Ticket\x12F\n" +
	"\bTicketID\x18\x01 \x01(\x03B*ʵ\x03&\xa2\x01#json:\"ticket_id\" binding:\"required\"R\bTicketID\x12L\n" +
	"\n" +
	"CategoryID\x18\x02 \x01(\x03B,ʵ\x03(\xa2\x01%json:\"category_id\" binding:\"required\"R\n" +
	"CategoryID\x12R\n" +
	"\fCategoryName\x18\x03 \x01(\tB.ʵ\x03*\xa2\x01'json:\"category_name\" binding:\"required\"R\fCategoryName\x12e\n" +
	"\x12ParentCategoryName\x18\x04 \x01(\tB5ʵ\x031\xa2\x01.json:\"parent_category_name\" binding:\"required\"R\x12ParentCategoryName\x12L\n" +
	"\bStatusID\x18\x05 \x01(\tB0ʵ\x03,\xa2\x01)json:\"status_id\" binding:\"required,len=3\"R\bStatusID\x12a\n" +
	"\x11StatusDescription\x18\x06 \x01(\tB3ʵ\x03/\xa2\x01,json:\"status_description\" binding:\"required\"R\x11StatusDescription\x12_\n" +
	"\x10StatusEmployeeID\x18\a \x01(\x03B3ʵ\x03/\xa2\x01,json:\"status_employee_id\" binding:\"required\"R\x10StatusEmployeeID\x12b\n" +
	"\x0fStatusGroupName\x18\b \x01(\tB3ʵ\x03/\xa2\x01,json:\"status_group_name\" binding:\"omitempty\"H\x00R\x0fStatusGroupName\x88\x01\x01\x12b\n" +
	"\x0fScenarioOrderID\x18\t \x01(\x03B3ʵ\x03/\xa2\x01,json:\"scenario_order_id\" binding:\"omitempty\"H\x01R\x0fScenarioOrderID\x88\x01\x01\x12X\n" +
	"\fScenarioName\x18\n" +
	" \x01(\tB/ʵ\x03+\xa2\x01(json:\"scenario_name\" binding:\"omitempty\"H\x02R\fScenarioName\x88\x01\x01\x12a\n" +
	"\x0fRejectedComment\x18\v \x01(\tB2ʵ\x03.\xa2\x01+json:\"rejected_comment\" binding:\"omitempty\"H\x03R\x0fRejectedComment\x88\x01\x01\x12Z\n" +
	"\x03Ext\x18\f \x03(\v2\x1c.sync_models.Tickets.ExtDataB*ʵ\x03&\xa2\x01#json:\"ext\" binding:\"omitempty,dive\"R\x03Ext\x12:\n" +
	"\x04ChDt\x18\r \x01(\tB&ʵ\x03\"\xa2\x01\x1fjson:\"ch_dt\" binding:\"required\"R\x04ChDt\x12_\n" +
	"\x10CreateEmployeeID\x18\x0e \x01(\x03B3ʵ\x03/\xa2\x01,json:\"create_employee_id\" binding:\"required\"R\x10CreateEmployeeID\x12F\n" +
	"\bCreateDt\x18\x0f \x01(\tB*ʵ\x03&\xa2\x01#json:\"create_dt\" binding:\"required\"R\bCreateDt\x12*\n" +
	"\x05LogId\x18d \x01(\x03B\x14ʵ\x03\x10\xa2\x01\rjson:\"log_id\"R\x05LogIdB\x12\n" +
	"\x10_StatusGroupNameB\x12\n" +
	"\x10_ScenarioOrderIDB\x0f\n" +
	"\r_ScenarioNameB\x12\n" +
	"\x10_RejectedComment\x1a\xff\x01\n" +
	"\aExtData\x12V\n" +
	"\rFrontDataName\x18\x01 \x01(\tB0ʵ\x03,\xa2\x01)json:\"front_data_name\" binding:\"required\"R\rFrontDataName\x12F\n" +
	"\bDataName\x18\x02 \x01(\tB*ʵ\x03&\xa2\x01#json:\"data_name\" binding:\"required\"R\bDataName\x12T\n" +
	"\x05Value\x18\x03 \x01(\v2\x16.google.protobuf.ValueB&ʵ\x03\"\xa2\x01\x1fjson:\"value\" binding:\"required\"R\x05ValueB\x0fZ\r./sync_modelsb\x06proto3"

var (
	file_support_tickets_changes_proto_rawDescOnce sync.Once
	file_support_tickets_changes_proto_rawDescData []byte
)

func file_support_tickets_changes_proto_rawDescGZIP() []byte {
	file_support_tickets_changes_proto_rawDescOnce.Do(func() {
		file_support_tickets_changes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_tickets_changes_proto_rawDesc), len(file_support_tickets_changes_proto_rawDesc)))
	})
	return file_support_tickets_changes_proto_rawDescData
}

var file_support_tickets_changes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_support_tickets_changes_proto_goTypes = []any{
	(*Tickets)(nil),         // 0: sync_models.Tickets
	(*Tickets_Ticket)(nil),  // 1: sync_models.Tickets.Ticket
	(*Tickets_ExtData)(nil), // 2: sync_models.Tickets.ExtData
	(*structpb.Value)(nil),  // 3: google.protobuf.Value
}
var file_support_tickets_changes_proto_depIdxs = []int32{
	1, // 0: sync_models.Tickets.Data:type_name -> sync_models.Tickets.Ticket
	2, // 1: sync_models.Tickets.Ticket.Ext:type_name -> sync_models.Tickets.ExtData
	3, // 2: sync_models.Tickets.ExtData.Value:type_name -> google.protobuf.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_support_tickets_changes_proto_init() }
func file_support_tickets_changes_proto_init() {
	if File_support_tickets_changes_proto != nil {
		return
	}
	file_support_tickets_changes_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_tickets_changes_proto_rawDesc), len(file_support_tickets_changes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_support_tickets_changes_proto_goTypes,
		DependencyIndexes: file_support_tickets_changes_proto_depIdxs,
		MessageInfos:      file_support_tickets_changes_proto_msgTypes,
	}.Build()
	File_support_tickets_changes_proto = out.File
	file_support_tickets_changes_proto_goTypes = nil
	file_support_tickets_changes_proto_depIdxs = nil
}
