// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: support.tickets.scenarios.proto

package sync_models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scenarios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Scenarios_Scenario  `protobuf:"bytes,1,rep,name=Data,proto3" json:"data" binding:"required,gt=0,dive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenarios) Reset() {
	*x = Scenarios{}
	mi := &file_support_tickets_scenarios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenarios) ProtoMessage() {}

func (x *Scenarios) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_scenarios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenarios.ProtoReflect.Descriptor instead.
func (*Scenarios) Descriptor() ([]byte, []int) {
	return file_support_tickets_scenarios_proto_rawDescGZIP(), []int{0}
}

func (x *Scenarios) GetData() []*Scenarios_Scenario {
	if x != nil {
		return x.Data
	}
	return nil
}

type Scenarios_Scenario struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CategoryID      int64                  `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"category_id" binding:"required"`
	StatusID        string                 `protobuf:"bytes,2,opt,name=StatusID,proto3" json:"status_id" binding:"required,len=3"`
	NextStatusID    string                 `protobuf:"bytes,3,opt,name=NextStatusID,proto3" json:"next_status_id" binding:"required,len=3"`
	ScenarioOrderID *int64                 `protobuf:"varint,4,opt,name=ScenarioOrderID,proto3,oneof" json:"scenario_order_id" binding:"omitempty"`
	ScenarioName    string                 `protobuf:"bytes,5,opt,name=ScenarioName,proto3" json:"scenario_name" binding:"required"`
	IsDel           *bool                  `protobuf:"varint,6,opt,name=IsDel,proto3,oneof" json:"is_del" binding:"required"`
	ChEmployeeID    int64                  `protobuf:"varint,7,opt,name=ChEmployeeID,proto3" json:"ch_employee_id" binding:"required"`
	ChDt            string                 `protobuf:"bytes,8,opt,name=ChDt,proto3" json:"ch_dt" binding:"required,IsRFC3339Nano"`
	LogId           int64                  `protobuf:"varint,100,opt,name=LogId,proto3" json:"log_id"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Scenarios_Scenario) Reset() {
	*x = Scenarios_Scenario{}
	mi := &file_support_tickets_scenarios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenarios_Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenarios_Scenario) ProtoMessage() {}

func (x *Scenarios_Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_scenarios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenarios_Scenario.ProtoReflect.Descriptor instead.
func (*Scenarios_Scenario) Descriptor() ([]byte, []int) {
	return file_support_tickets_scenarios_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Scenarios_Scenario) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Scenarios_Scenario) GetStatusID() string {
	if x != nil {
		return x.StatusID
	}
	return ""
}

func (x *Scenarios_Scenario) GetNextStatusID() string {
	if x != nil {
		return x.NextStatusID
	}
	return ""
}

func (x *Scenarios_Scenario) GetScenarioOrderID() int64 {
	if x != nil && x.ScenarioOrderID != nil {
		return *x.ScenarioOrderID
	}
	return 0
}

func (x *Scenarios_Scenario) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *Scenarios_Scenario) GetIsDel() bool {
	if x != nil && x.IsDel != nil {
		return *x.IsDel
	}
	return false
}

func (x *Scenarios_Scenario) GetChEmployeeID() int64 {
	if x != nil {
		return x.ChEmployeeID
	}
	return 0
}

func (x *Scenarios_Scenario) GetChDt() string {
	if x != nil {
		return x.ChDt
	}
	return ""
}

func (x *Scenarios_Scenario) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

var File_support_tickets_scenarios_proto protoreflect.FileDescriptor

const file_support_tickets_scenarios_proto_rawDesc = "" +
	"\n" +
	"\x1fsupport.tickets.scenarios.proto\x12\vsync_models\x1a)github.com/alta/protopatch/patch/go.proto\"\xda\x06\n" +
	"\tScenarios\x12d\n" +
	"\x04Data\x18\x01 \x03(\v2\x1f.sync_models.Scenarios.ScenarioB/ʵ\x03+\xa2\x01(json:\"data\" binding:\"required,gt=0,dive\"R\x04Data\x1a\xe6\x05\n" +
	"\bScenario\x12L\n" +
	"\n" +
	"CategoryID\x18\x01 \x01(\x03B,ʵ\x03(\xa2\x01%json:\"category_id\" binding:\"required\"R\n" +
	"CategoryID\x12L\n" +
	"\bStatusID\x18\x02 \x01(\tB0ʵ\x03,\xa2\x01)json:\"status_id\" binding:\"required,len=3\"R\bStatusID\x12Y\n" +
	"\fNextStatusID\x18\x03 \x01(\tB5ʵ\x031\xa2\x01.json:\"next_status_id\" binding:\"required,len=3\"R\fNextStatusID\x12b\n" +
	"\x0fScenarioOrderID\x18\x04 \x01(\x03B3ʵ\x03/\xa2\x01,json:\"scenario_order_id\" binding:\"omitempty\"H\x00R\x0fScenarioOrderID\x88\x01\x01\x12R\n" +
	"\fScenarioName\x18\x05 \x01(\tB.ʵ\x03*\xa2\x01'json:\"scenario_name\" binding:\"required\"R\fScenarioName\x12B\n" +
	"\x05IsDel\x18\x06 \x01(\bB'ʵ\x03#\xa2\x01 json:\"is_del\" binding:\"required\"H\x01R\x05IsDel\x88\x01\x01\x12S\n" +
	"\fChEmployeeID\x18\a \x01(\x03B/ʵ\x03+\xa2\x01(json:\"ch_employee_id\" binding:\"required\"R\fChEmployeeID\x12H\n" +
	"\x04ChDt\x18\b \x01(\tB4ʵ\x030\xa2\x01-json:\"ch_dt\" binding:\"required,IsRFC3339Nano\"R\x04ChDt\x12*\n" +
	"\x05LogId\x18d \x01(\x03B\x14ʵ\x03\x10\xa2\x01\rjson:\"log_id\"R\x05LogIdB\x12\n" +
	"\x10_ScenarioOrderIDB\b\n" +
	"\x06_IsDelB\x0fZ\r./sync_modelsb\x06proto3"

var (
	file_support_tickets_scenarios_proto_rawDescOnce sync.Once
	file_support_tickets_scenarios_proto_rawDescData []byte
)

func file_support_tickets_scenarios_proto_rawDescGZIP() []byte {
	file_support_tickets_scenarios_proto_rawDescOnce.Do(func() {
		file_support_tickets_scenarios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_tickets_scenarios_proto_rawDesc), len(file_support_tickets_scenarios_proto_rawDesc)))
	})
	return file_support_tickets_scenarios_proto_rawDescData
}

var file_support_tickets_scenarios_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_support_tickets_scenarios_proto_goTypes = []any{
	(*Scenarios)(nil),          // 0: sync_models.Scenarios
	(*Scenarios_Scenario)(nil), // 1: sync_models.Scenarios.Scenario
}
var file_support_tickets_scenarios_proto_depIdxs = []int32{
	1, // 0: sync_models.Scenarios.Data:type_name -> sync_models.Scenarios.Scenario
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_support_tickets_scenarios_proto_init() }
func file_support_tickets_scenarios_proto_init() {
	if File_support_tickets_scenarios_proto != nil {
		return
	}
	file_support_tickets_scenarios_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_tickets_scenarios_proto_rawDesc), len(file_support_tickets_scenarios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_support_tickets_scenarios_proto_goTypes,
		DependencyIndexes: file_support_tickets_scenarios_proto_depIdxs,
		MessageInfos:      file_support_tickets_scenarios_proto_msgTypes,
	}.Build()
	File_support_tickets_scenarios_proto = out.File
	file_support_tickets_scenarios_proto_goTypes = nil
	file_support_tickets_scenarios_proto_depIdxs = nil
}
