// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: support.tickets.categories.proto

package sync_models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Categories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Categories_Category `protobuf:"bytes,1,rep,name=Data,proto3" json:"data" binding:"required,gt=0,dive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categories) Reset() {
	*x = Categories{}
	mi := &file_support_tickets_categories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categories) ProtoMessage() {}

func (x *Categories) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_categories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categories.ProtoReflect.Descriptor instead.
func (*Categories) Descriptor() ([]byte, []int) {
	return file_support_tickets_categories_proto_rawDescGZIP(), []int{0}
}

func (x *Categories) GetData() []*Categories_Category {
	if x != nil {
		return x.Data
	}
	return nil
}

type Categories_Category struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryID         int64                  `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"category_id" binding:"required"`
	CategoryName       string                 `protobuf:"bytes,2,opt,name=CategoryName,proto3" json:"category_name" binding:"required"`
	IsDel              *bool                  `protobuf:"varint,3,opt,name=IsDel,proto3,oneof" json:"is_del" binding:"required"`
	ParentCategoryID   int64                  `protobuf:"varint,4,opt,name=ParentCategoryID,proto3" json:"parent_category_id" binding:"required"`
	ParentCategoryName string                 `protobuf:"bytes,5,opt,name=ParentCategoryName,proto3" json:"parent_category_name" binding:"required"`
	ActionID           *string                `protobuf:"bytes,6,opt,name=ActionID,proto3,oneof" json:"action_id" binding:"omitempty"`
	ChEmployeeID       int64                  `protobuf:"varint,7,opt,name=ChEmployeeID,proto3" json:"ch_employee_id" binding:"required"`
	ChDt               string                 `protobuf:"bytes,8,opt,name=ChDt,proto3" json:"ch_dt" binding:"required"`
	ChildCategoryIDs   []int64                `protobuf:"varint,9,rep,packed,name=ChildCategoryIDs,proto3" json:"child_category_ids" binding:"omitempty,dive"`
	IsProd             *bool                  `protobuf:"varint,10,opt,name=IsProd,proto3,oneof" json:"is_prod" binding:"omitempty"`
	SyncDt             *string                `protobuf:"bytes,11,opt,name=SyncDt,proto3,oneof" json:"sync_dt" binding:"omitempty"`
	SourceCategoryID   *int64                 `protobuf:"varint,12,opt,name=SourceCategoryID,proto3,oneof" json:"source_category_id" binding:"omitempty"`
	ProdCategoryIDs    []int64                `protobuf:"varint,13,rep,packed,name=ProdCategoryIDs,proto3" json:"prod_category_ids" binding:"omitempty,dive"`
	LogId              int64                  `protobuf:"varint,100,opt,name=LogId,proto3" json:"log_id"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Categories_Category) Reset() {
	*x = Categories_Category{}
	mi := &file_support_tickets_categories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categories_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categories_Category) ProtoMessage() {}

func (x *Categories_Category) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_categories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categories_Category.ProtoReflect.Descriptor instead.
func (*Categories_Category) Descriptor() ([]byte, []int) {
	return file_support_tickets_categories_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Categories_Category) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Categories_Category) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Categories_Category) GetIsDel() bool {
	if x != nil && x.IsDel != nil {
		return *x.IsDel
	}
	return false
}

func (x *Categories_Category) GetParentCategoryID() int64 {
	if x != nil {
		return x.ParentCategoryID
	}
	return 0
}

func (x *Categories_Category) GetParentCategoryName() string {
	if x != nil {
		return x.ParentCategoryName
	}
	return ""
}

func (x *Categories_Category) GetActionID() string {
	if x != nil && x.ActionID != nil {
		return *x.ActionID
	}
	return ""
}

func (x *Categories_Category) GetChEmployeeID() int64 {
	if x != nil {
		return x.ChEmployeeID
	}
	return 0
}

func (x *Categories_Category) GetChDt() string {
	if x != nil {
		return x.ChDt
	}
	return ""
}

func (x *Categories_Category) GetChildCategoryIDs() []int64 {
	if x != nil {
		return x.ChildCategoryIDs
	}
	return nil
}

func (x *Categories_Category) GetIsProd() bool {
	if x != nil && x.IsProd != nil {
		return *x.IsProd
	}
	return false
}

func (x *Categories_Category) GetSyncDt() string {
	if x != nil && x.SyncDt != nil {
		return *x.SyncDt
	}
	return ""
}

func (x *Categories_Category) GetSourceCategoryID() int64 {
	if x != nil && x.SourceCategoryID != nil {
		return *x.SourceCategoryID
	}
	return 0
}

func (x *Categories_Category) GetProdCategoryIDs() []int64 {
	if x != nil {
		return x.ProdCategoryIDs
	}
	return nil
}

func (x *Categories_Category) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

var File_support_tickets_categories_proto protoreflect.FileDescriptor

const file_support_tickets_categories_proto_rawDesc = "" +
	"\n" +
	" support.tickets.categories.proto\x12\vsync_models\x1a)github.com/alta/protopatch/patch/go.proto\"\xbd\n" +
	"\n" +
	"\n" +
	"Categories\x12e\n" +
	"\x04Data\x18\x01 \x03(\v2 .sync_models.Categories.CategoryB/ʵ\x03+\xa2\x01(json:\"data\" binding:\"required,gt=0,dive\"R\x04Data\x1a\xc7\t\n" +
	"\bCategory\x12L\n" +
	"\n" +
	"CategoryID\x18\x01 \x01(\x03B,ʵ\x03(\xa2\x01%json:\"category_id\" binding:\"required\"R\n" +
	"CategoryID\x12R\n" +
	"\fCategoryName\x18\x02 \x01(\tB.ʵ\x03*\xa2\x01'json:\"category_name\" binding:\"required\"R\fCategoryName\x12B\n" +
	"\x05IsDel\x18\x03 \x01(\bB'ʵ\x03#\xa2\x01 json:\"is_del\" binding:\"required\"H\x00R\x05IsDel\x88\x01\x01\x12_\n" +
	"\x10ParentCategoryID\x18\x04 \x01(\x03B3ʵ\x03/\xa2\x01,json:\"parent_category_id\" binding:\"required\"R\x10ParentCategoryID\x12e\n" +
	"\x12ParentCategoryName\x18\x05 \x01(\tB5ʵ\x031\xa2\x01.json:\"parent_category_name\" binding:\"required\"R\x12ParentCategoryName\x12L\n" +
	"\bActionID\x18\x06 \x01(\tB+ʵ\x03'\xa2\x01$json:\"action_id\" binding:\"omitempty\"H\x01R\bActionID\x88\x01\x01\x12S\n" +
	"\fChEmployeeID\x18\a \x01(\x03B/ʵ\x03+\xa2\x01(json:\"ch_employee_id\" binding:\"required\"R\fChEmployeeID\x12:\n" +
	"\x04ChDt\x18\b \x01(\tB&ʵ\x03\"\xa2\x01\x1fjson:\"ch_dt\" binding:\"required\"R\x04ChDt\x12e\n" +
	"\x10ChildCategoryIDs\x18\t \x03(\x03B9ʵ\x035\xa2\x012json:\"child_category_ids\" binding:\"omitempty,dive\"R\x10ChildCategoryIDs\x12F\n" +
	"\x06IsProd\x18\n" +
	" \x01(\bB)ʵ\x03%\xa2\x01\"json:\"is_prod\" binding:\"omitempty\"H\x02R\x06IsProd\x88\x01\x01\x12F\n" +
	"\x06SyncDt\x18\v \x01(\tB)ʵ\x03%\xa2\x01\"json:\"sync_dt\" binding:\"omitempty\"H\x03R\x06SyncDt\x88\x01\x01\x12e\n" +
	"\x10SourceCategoryID\x18\f \x01(\x03B4ʵ\x030\xa2\x01-json:\"source_category_id\" binding:\"omitempty\"H\x04R\x10SourceCategoryID\x88\x01\x01\x12b\n" +
	"\x0fProdCategoryIDs\x18\r \x03(\x03B8ʵ\x034\xa2\x011json:\"prod_category_ids\" binding:\"omitempty,dive\"R\x0fProdCategoryIDs\x12*\n" +
	"\x05LogId\x18d \x01(\x03B\x14ʵ\x03\x10\xa2\x01\rjson:\"log_id\"R\x05LogIdB\b\n" +
	"\x06_IsDelB\v\n" +
	"\t_ActionIDB\t\n" +
	"\a_IsProdB\t\n" +
	"\a_SyncDtB\x13\n" +
	"\x11_SourceCategoryIDB\x0fZ\r./sync_modelsb\x06proto3"

var (
	file_support_tickets_categories_proto_rawDescOnce sync.Once
	file_support_tickets_categories_proto_rawDescData []byte
)

func file_support_tickets_categories_proto_rawDescGZIP() []byte {
	file_support_tickets_categories_proto_rawDescOnce.Do(func() {
		file_support_tickets_categories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_tickets_categories_proto_rawDesc), len(file_support_tickets_categories_proto_rawDesc)))
	})
	return file_support_tickets_categories_proto_rawDescData
}

var file_support_tickets_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_support_tickets_categories_proto_goTypes = []any{
	(*Categories)(nil),          // 0: sync_models.Categories
	(*Categories_Category)(nil), // 1: sync_models.Categories.Category
}
var file_support_tickets_categories_proto_depIdxs = []int32{
	1, // 0: sync_models.Categories.Data:type_name -> sync_models.Categories.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_support_tickets_categories_proto_init() }
func file_support_tickets_categories_proto_init() {
	if File_support_tickets_categories_proto != nil {
		return
	}
	file_support_tickets_categories_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_tickets_categories_proto_rawDesc), len(file_support_tickets_categories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_support_tickets_categories_proto_goTypes,
		DependencyIndexes: file_support_tickets_categories_proto_depIdxs,
		MessageInfos:      file_support_tickets_categories_proto_msgTypes,
	}.Build()
	File_support_tickets_categories_proto = out.File
	file_support_tickets_categories_proto_goTypes = nil
	file_support_tickets_categories_proto_depIdxs = nil
}
