// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: support.tickets.groups.proto

package sync_models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Groups struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Groups_Group        `protobuf:"bytes,1,rep,name=Data,proto3" json:"data" binding:"required,gt=0,dive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Groups) Reset() {
	*x = Groups{}
	mi := &file_support_tickets_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Groups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Groups) ProtoMessage() {}

func (x *Groups) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Groups.ProtoReflect.Descriptor instead.
func (*Groups) Descriptor() ([]byte, []int) {
	return file_support_tickets_groups_proto_rawDescGZIP(), []int{0}
}

func (x *Groups) GetData() []*Groups_Group {
	if x != nil {
		return x.Data
	}
	return nil
}

type Groups_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       int64                  `protobuf:"varint,1,opt,name=GroupID,proto3" json:"group_id" binding:"required"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=GroupName,proto3" json:"group_name" binding:"required"`
	IsDel         *bool                  `protobuf:"varint,3,opt,name=IsDel,proto3,oneof" json:"is_del" binding:"required"`
	ChEmployeeID  int64                  `protobuf:"varint,4,opt,name=ChEmployeeID,proto3" json:"ch_employee_id" binding:"required"`
	ChDt          string                 `protobuf:"bytes,5,opt,name=ChDt,proto3" json:"ch_dt" binding:"required,IsRFC3339Nano"`
	LogId         int64                  `protobuf:"varint,100,opt,name=LogId,proto3" json:"log_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Groups_Group) Reset() {
	*x = Groups_Group{}
	mi := &file_support_tickets_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Groups_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Groups_Group) ProtoMessage() {}

func (x *Groups_Group) ProtoReflect() protoreflect.Message {
	mi := &file_support_tickets_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Groups_Group.ProtoReflect.Descriptor instead.
func (*Groups_Group) Descriptor() ([]byte, []int) {
	return file_support_tickets_groups_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Groups_Group) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *Groups_Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Groups_Group) GetIsDel() bool {
	if x != nil && x.IsDel != nil {
		return *x.IsDel
	}
	return false
}

func (x *Groups_Group) GetChEmployeeID() int64 {
	if x != nil {
		return x.ChEmployeeID
	}
	return 0
}

func (x *Groups_Group) GetChDt() string {
	if x != nil {
		return x.ChDt
	}
	return ""
}

func (x *Groups_Group) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

var File_support_tickets_groups_proto protoreflect.FileDescriptor

const file_support_tickets_groups_proto_rawDesc = "" +
	"\n" +
	"\x1csupport.tickets.groups.proto\x12\vsync_models\x1a)github.com/alta/protopatch/patch/go.proto\"\x9b\x04\n" +
	"\x06Groups\x12^\n" +
	"\x04Data\x18\x01 \x03(\v2\x19.sync_models.Groups.GroupB/ʵ\x03+\xa2\x01(json:\"data\" binding:\"required,gt=0,dive\"R\x04Data\x1a\xb0\x03\n" +
	"\x05Group\x12C\n" +
	"\aGroupID\x18\x01 \x01(\x03B)ʵ\x03%\xa2\x01\"json:\"group_id\" binding:\"required\"R\aGroupID\x12I\n" +
	"\tGroupName\x18\x02 \x01(\tB+ʵ\x03'\xa2\x01$json:\"group_name\" binding:\"required\"R\tGroupName\x12B\n" +
	"\x05IsDel\x18\x03 \x01(\bB'ʵ\x03#\xa2\x01 json:\"is_del\" binding:\"required\"H\x00R\x05IsDel\x88\x01\x01\x12S\n" +
	"\fChEmployeeID\x18\x04 \x01(\x03B/ʵ\x03+\xa2\x01(json:\"ch_employee_id\" binding:\"required\"R\fChEmployeeID\x12H\n" +
	"\x04ChDt\x18\x05 \x01(\tB4ʵ\x030\xa2\x01-json:\"ch_dt\" binding:\"required,IsRFC3339Nano\"R\x04ChDt\x12*\n" +
	"\x05LogId\x18d \x01(\x03B\x14ʵ\x03\x10\xa2\x01\rjson:\"log_id\"R\x05LogIdB\b\n" +
	"\x06_IsDelB\x0fZ\r./sync_modelsb\x06proto3"

var (
	file_support_tickets_groups_proto_rawDescOnce sync.Once
	file_support_tickets_groups_proto_rawDescData []byte
)

func file_support_tickets_groups_proto_rawDescGZIP() []byte {
	file_support_tickets_groups_proto_rawDescOnce.Do(func() {
		file_support_tickets_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_tickets_groups_proto_rawDesc), len(file_support_tickets_groups_proto_rawDesc)))
	})
	return file_support_tickets_groups_proto_rawDescData
}

var file_support_tickets_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_support_tickets_groups_proto_goTypes = []any{
	(*Groups)(nil),       // 0: sync_models.Groups
	(*Groups_Group)(nil), // 1: sync_models.Groups.Group
}
var file_support_tickets_groups_proto_depIdxs = []int32{
	1, // 0: sync_models.Groups.Data:type_name -> sync_models.Groups.Group
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_support_tickets_groups_proto_init() }
func file_support_tickets_groups_proto_init() {
	if File_support_tickets_groups_proto != nil {
		return
	}
	file_support_tickets_groups_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_tickets_groups_proto_rawDesc), len(file_support_tickets_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_support_tickets_groups_proto_goTypes,
		DependencyIndexes: file_support_tickets_groups_proto_depIdxs,
		MessageInfos:      file_support_tickets_groups_proto_msgTypes,
	}.Build()
	File_support_tickets_groups_proto = out.File
	file_support_tickets_groups_proto_goTypes = nil
	file_support_tickets_groups_proto_depIdxs = nil
}
