// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tickets.status.change.proto

package sync_models

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Tickets struct {
	Data []Tickets_TicketData `protobuf:"bytes,1,rep,name=Data,proto3" json:"data"`
}

func (m *Tickets) Reset()         { *m = Tickets{} }
func (m *Tickets) String() string { return proto.CompactTextString(m) }
func (*Tickets) ProtoMessage()    {}
func (*Tickets) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dea3713b61b21a, []int{0}
}
func (m *Tickets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tickets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tickets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tickets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tickets.Merge(m, src)
}
func (m *Tickets) XXX_Size() int {
	return m.Size()
}
func (m *Tickets) XXX_DiscardUnknown() {
	xxx_messageInfo_Tickets.DiscardUnknown(m)
}

var xxx_messageInfo_Tickets proto.InternalMessageInfo

type Tickets_TicketData struct {
	Ext               *string `protobuf:"bytes,1,opt,name=Ext,proto3,wktptr" json:"ext"`
	ChDt              string  `protobuf:"bytes,2,opt,name=ChDt,proto3" json:"ch_dt"`
	ChEmployeeID      int64   `protobuf:"varint,3,opt,name=ChEmployeeID,proto3" json:"ch_employee_id"`
	CreateDt          string  `protobuf:"bytes,4,opt,name=CreateDt,proto3" json:"create_dt"`
	TicketID          int64   `protobuf:"varint,5,opt,name=TicketID,proto3" json:"ticket_id"`
	CategoryID        int64   `protobuf:"varint,6,opt,name=CategoryID,proto3" json:"category_id"`
	StatusId          string  `protobuf:"bytes,7,opt,name=status_id,json=statusId,proto3" json:"status_id"`
	Comments          *string `protobuf:"bytes,8,opt,name=Comments,proto3,wktptr" json:"comments"`
	RejectedComments  *string `protobuf:"bytes,9,opt,name=RejectedComments,proto3,wktptr" json:"rejected_comments"`
	CreateEmployeeID  int64   `protobuf:"varint,10,opt,name=CreateEmployeeID,proto3" json:"create_employee_id"`
	ApproveEmployeeID *int64  `protobuf:"bytes,11,opt,name=ApproveEmployeeID,proto3,wktptr" json:"approve_employee_id"`
	PerformEmployeeID *int64  `protobuf:"bytes,12,opt,name=PerformEmployeeID,proto3,wktptr" json:"perform_employee_id"`
}

func (m *Tickets_TicketData) Reset()         { *m = Tickets_TicketData{} }
func (m *Tickets_TicketData) String() string { return proto.CompactTextString(m) }
func (*Tickets_TicketData) ProtoMessage()    {}
func (*Tickets_TicketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dea3713b61b21a, []int{0, 0}
}
func (m *Tickets_TicketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tickets_TicketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tickets_TicketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tickets_TicketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tickets_TicketData.Merge(m, src)
}
func (m *Tickets_TicketData) XXX_Size() int {
	return m.Size()
}
func (m *Tickets_TicketData) XXX_DiscardUnknown() {
	xxx_messageInfo_Tickets_TicketData.DiscardUnknown(m)
}

var xxx_messageInfo_Tickets_TicketData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Tickets)(nil), "sync_models.Tickets")
	proto.RegisterType((*Tickets_TicketData)(nil), "sync_models.Tickets.TicketData")
}

func init() { proto.RegisterFile("tickets.status.change.proto", fileDescriptor_76dea3713b61b21a) }

var fileDescriptor_76dea3713b61b21a = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x8f, 0xd2, 0x40,
	0x14, 0xa7, 0xc2, 0xb2, 0x30, 0x45, 0x65, 0xc7, 0xc4, 0x54, 0x58, 0x3b, 0xc4, 0x13, 0x9a, 0x58,
	0x92, 0xd5, 0xec, 0xc5, 0xd3, 0x96, 0xee, 0x01, 0x4f, 0xa6, 0x1a, 0xaf, 0xcd, 0x30, 0x1d, 0x5a,
	0x94, 0x32, 0x4d, 0x3b, 0xe8, 0xf2, 0x2d, 0x3c, 0x7a, 0xf4, 0xe3, 0x70, 0xdc, 0xa3, 0xa7, 0x51,
	0xe1, 0x60, 0xd2, 0x4f, 0x61, 0x3a, 0x53, 0xa1, 0x9b, 0x5e, 0x38, 0x75, 0xde, 0x7b, 0xbf, 0x7f,
	0x7d, 0x0f, 0xf4, 0xf9, 0x9c, 0x7c, 0xa6, 0x3c, 0xb5, 0x52, 0x8e, 0xf9, 0x2a, 0xb5, 0x48, 0x88,
	0x97, 0x01, 0xb5, 0xe2, 0x84, 0x71, 0x06, 0xf5, 0x74, 0xbd, 0x24, 0x5e, 0xc4, 0x7c, 0xba, 0x48,
	0x7b, 0x2f, 0x83, 0x39, 0x0f, 0x57, 0x53, 0x8b, 0xb0, 0x68, 0x14, 0xb0, 0x80, 0x8d, 0x24, 0x66,
	0xba, 0x9a, 0xc9, 0x4a, 0x16, 0xf2, 0xa5, 0xb8, 0x3d, 0x33, 0x60, 0x2c, 0x58, 0xd0, 0x03, 0xea,
	0x6b, 0x82, 0xe3, 0x98, 0x26, 0xa9, 0x9a, 0x3f, 0xfb, 0xdb, 0x04, 0xa7, 0x1f, 0x94, 0x37, 0xbc,
	0x02, 0x0d, 0x07, 0x73, 0x6c, 0x68, 0x83, 0xfa, 0x50, 0xbf, 0x40, 0x56, 0xc9, 0xd6, 0x2a, 0x30,
	0xc5, 0x37, 0x87, 0xd9, 0x9d, 0x8d, 0x40, 0xb5, 0x4c, 0xa0, 0x86, 0x8f, 0x39, 0x76, 0x25, 0xb5,
	0xf7, 0xbd, 0x09, 0xc0, 0x01, 0x02, 0xdf, 0x80, 0xfa, 0xf5, 0x0d, 0x37, 0xb4, 0x81, 0x36, 0xd4,
	0x2f, 0xce, 0x2d, 0x95, 0xc5, 0xfa, 0x9f, 0xc5, 0x7a, 0xcf, 0x93, 0xf9, 0x32, 0xf8, 0x88, 0x17,
	0x2b, 0x6a, 0xeb, 0x99, 0x40, 0x75, 0x7a, 0xc3, 0x7f, 0xfc, 0x42, 0x9a, 0x9b, 0xb3, 0xe0, 0x53,
	0xd0, 0x18, 0x87, 0x0e, 0x37, 0xee, 0x0d, 0xb4, 0x61, 0xdb, 0x6e, 0x67, 0x02, 0x9d, 0x90, 0xd0,
	0xf3, 0xb9, 0x2b, 0xdb, 0xf0, 0x12, 0x74, 0xc6, 0xe1, 0x75, 0x14, 0x2f, 0xd8, 0x9a, 0xd2, 0x89,
	0x63, 0xd4, 0x07, 0xda, 0xb0, 0x6e, 0xc3, 0x4c, 0xa0, 0x07, 0x24, 0xf4, 0x68, 0x31, 0xf0, 0xe6,
	0xbe, 0x7b, 0x07, 0x07, 0x9f, 0x83, 0xd6, 0x38, 0xa1, 0x98, 0x53, 0x87, 0x1b, 0x0d, 0x29, 0x7d,
	0x3f, 0x13, 0xa8, 0x4d, 0x64, 0x2f, 0x97, 0xdf, 0x8f, 0x73, 0xa8, 0xfa, 0x99, 0x89, 0x63, 0x9c,
	0x48, 0x79, 0x09, 0x55, 0xb7, 0xca, 0x95, 0xf7, 0x63, 0x38, 0x02, 0x60, 0x8c, 0x39, 0x0d, 0x58,
	0xb2, 0x9e, 0x38, 0x46, 0x53, 0x82, 0x1f, 0x66, 0x02, 0xe9, 0xa4, 0xe8, 0xe6, 0xf0, 0x12, 0x04,
	0xbe, 0x00, 0x6d, 0x75, 0x6b, 0x6f, 0xee, 0x1b, 0xa7, 0x87, 0x1c, 0xfb, 0xa6, 0xdb, 0x52, 0xcf,
	0x89, 0x0f, 0xdf, 0x82, 0xd6, 0x98, 0x45, 0x11, 0x5d, 0xf2, 0xd4, 0x68, 0x1d, 0xb1, 0xcb, 0x6e,
	0x26, 0x50, 0x8b, 0x14, 0x0c, 0xb9, 0xd0, 0x3d, 0x1f, 0x12, 0xd0, 0x75, 0xe9, 0x27, 0x4a, 0x38,
	0xf5, 0xf7, 0x9a, 0xed, 0x23, 0x34, 0x9f, 0x64, 0x02, 0x9d, 0x25, 0x05, 0xd3, 0xbb, 0x23, 0x5e,
	0x11, 0x84, 0x36, 0xe8, 0xaa, 0x25, 0x96, 0xee, 0x03, 0xe4, 0x4e, 0x1e, 0x67, 0x02, 0xc1, 0x62,
	0xd7, 0xe5, 0x1b, 0x55, 0xf0, 0x70, 0x06, 0xce, 0xae, 0xe2, 0x38, 0x61, 0x5f, 0xca, 0x22, 0xba,
	0x4c, 0xda, 0xaf, 0x24, 0x9d, 0x2c, 0xf9, 0xe5, 0x6b, 0x15, 0xb4, 0x9f, 0x09, 0xf4, 0x08, 0x2b,
	0x66, 0xd9, 0x42, 0x46, 0xad, 0x4a, 0xe6, 0x3e, 0xef, 0x68, 0x32, 0x63, 0x49, 0x54, 0xf2, 0xe9,
	0x1c, 0xe9, 0x13, 0x2b, 0x66, 0xd5, 0xa7, 0x22, 0x69, 0x9f, 0x6f, 0xfe, 0x98, 0xb5, 0xcd, 0xd6,
	0xd4, 0x6e, 0xb7, 0xa6, 0xf6, 0x7b, 0x6b, 0x6a, 0xdf, 0x76, 0x66, 0xed, 0x76, 0x67, 0xd6, 0x7e,
	0xee, 0xcc, 0xda, 0xb4, 0x29, 0x2d, 0x5e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x56, 0x96,
	0xbd, 0x09, 0x04, 0x00, 0x00,
}

func (m *Tickets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tickets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tickets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Data[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTicketsStatusChange(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Tickets_TicketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tickets_TicketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tickets_TicketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PerformEmployeeID != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdInt64MarshalTo(*m.PerformEmployeeID, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdInt64(*m.PerformEmployeeID):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x62
	}
	if m.ApproveEmployeeID != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdInt64MarshalTo(*m.ApproveEmployeeID, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdInt64(*m.ApproveEmployeeID):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreateEmployeeID != 0 {
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(m.CreateEmployeeID))
		i--
		dAtA[i] = 0x50
	}
	if m.RejectedComments != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdStringMarshalTo(*m.RejectedComments, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdString(*m.RejectedComments):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x4a
	}
	if m.Comments != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdStringMarshalTo(*m.Comments, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdString(*m.Comments):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x42
	}
	if len(m.StatusId) > 0 {
		i -= len(m.StatusId)
		copy(dAtA[i:], m.StatusId)
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(len(m.StatusId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.CategoryID != 0 {
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(m.CategoryID))
		i--
		dAtA[i] = 0x30
	}
	if m.TicketID != 0 {
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(m.TicketID))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CreateDt) > 0 {
		i -= len(m.CreateDt)
		copy(dAtA[i:], m.CreateDt)
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(len(m.CreateDt)))
		i--
		dAtA[i] = 0x22
	}
	if m.ChEmployeeID != 0 {
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(m.ChEmployeeID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChDt) > 0 {
		i -= len(m.ChDt)
		copy(dAtA[i:], m.ChDt)
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(len(m.ChDt)))
		i--
		dAtA[i] = 0x12
	}
	if m.Ext != nil {
		n5, err5 := github_com_gogo_protobuf_types.StdStringMarshalTo(*m.Ext, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdString(*m.Ext):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintTicketsStatusChange(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTicketsStatusChange(dAtA []byte, offset int, v uint64) int {
	offset -= sovTicketsStatusChange(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Tickets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovTicketsStatusChange(uint64(l))
		}
	}
	return n
}

func (m *Tickets_TicketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ext != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdString(*m.Ext)
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	l = len(m.ChDt)
	if l > 0 {
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.ChEmployeeID != 0 {
		n += 1 + sovTicketsStatusChange(uint64(m.ChEmployeeID))
	}
	l = len(m.CreateDt)
	if l > 0 {
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.TicketID != 0 {
		n += 1 + sovTicketsStatusChange(uint64(m.TicketID))
	}
	if m.CategoryID != 0 {
		n += 1 + sovTicketsStatusChange(uint64(m.CategoryID))
	}
	l = len(m.StatusId)
	if l > 0 {
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.Comments != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdString(*m.Comments)
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.RejectedComments != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdString(*m.RejectedComments)
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.CreateEmployeeID != 0 {
		n += 1 + sovTicketsStatusChange(uint64(m.CreateEmployeeID))
	}
	if m.ApproveEmployeeID != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdInt64(*m.ApproveEmployeeID)
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	if m.PerformEmployeeID != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdInt64(*m.PerformEmployeeID)
		n += 1 + l + sovTicketsStatusChange(uint64(l))
	}
	return n
}

func sovTicketsStatusChange(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTicketsStatusChange(x uint64) (n int) {
	return sovTicketsStatusChange(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Tickets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicketsStatusChange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tickets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tickets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, Tickets_TicketData{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTicketsStatusChange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tickets_TicketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicketsStatusChange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TicketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TicketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ext == nil {
				m.Ext = new(string)
			}
			if err := github_com_gogo_protobuf_types.StdStringUnmarshal(m.Ext, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChDt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChDt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChEmployeeID", wireType)
			}
			m.ChEmployeeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChEmployeeID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateDt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateDt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicketID", wireType)
			}
			m.TicketID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TicketID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CategoryID", wireType)
			}
			m.CategoryID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CategoryID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Comments == nil {
				m.Comments = new(string)
			}
			if err := github_com_gogo_protobuf_types.StdStringUnmarshal(m.Comments, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedComments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RejectedComments == nil {
				m.RejectedComments = new(string)
			}
			if err := github_com_gogo_protobuf_types.StdStringUnmarshal(m.RejectedComments, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateEmployeeID", wireType)
			}
			m.CreateEmployeeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateEmployeeID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApproveEmployeeID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ApproveEmployeeID == nil {
				m.ApproveEmployeeID = new(int64)
			}
			if err := github_com_gogo_protobuf_types.StdInt64Unmarshal(m.ApproveEmployeeID, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerformEmployeeID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PerformEmployeeID == nil {
				m.PerformEmployeeID = new(int64)
			}
			if err := github_com_gogo_protobuf_types.StdInt64Unmarshal(m.PerformEmployeeID, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTicketsStatusChange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicketsStatusChange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTicketsStatusChange(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTicketsStatusChange
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicketsStatusChange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTicketsStatusChange
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTicketsStatusChange
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTicketsStatusChange
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTicketsStatusChange        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTicketsStatusChange          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTicketsStatusChange = fmt.Errorf("proto: unexpected end of group")
)
